---
name: "Build system for nix-darwin"
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  check_evaluation_m1:
    runs-on: macos-14 # The processor on this label is M1, not x86_64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Build with nix-darwin
        run: nix run --extra-experimental-features 'nix-command flakes' nix-darwin -- build --flake .#walled-garden
